server:
  port: 8000

spring:
  application:
    name: miaosha
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2020
    username: root
    password: root
  redis:
    host: 192.168.220.135
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zjy.entity
logging:
  level:
    com.zjy.mapper: debug
